# Change these first
owner: AndreyBrigunet # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  -  AndreyBrigunet
  
sites:
  - name: Easy4Live.com
    url: https://easy4live.com
    icon: https://easy4live.com/assets/img/favicon.png
    maxResponseTime: 50000
  - name: Go.Easy4Live.com
    url: http://go.easy4live.com
    icon: https://easy4live.com/assets/img/favicon.png
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: RTMP Go.Easy4Live.com
    check: "tcp-ping"
    url: 185.225.17.60
    port: 1935
    icon: https://easy4live.com/assets/img/favicon.png
    maxResponseTime: 30000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.easy4live.com
  # baseUrl: /upptime
  logoUrl: https://easy4live.com/assets/img/favicon.png
  name: Easy4Live Status
  introTitle: "**Easy4Live Status** is the uptime monitor and status page"
  introMessage:  Our status page uses a **real-time** data from our [Easy4Live](https://easy4live.com) servers.
  navbar:
    - title: Main Page
      href: https://easy4live.com/

i18n:
  footer: This page is [open source]($REPO)
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
